services:
  - name: cowrywise-bot
    type: web
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "7637161395:AAF6T9HsFUi3qCFMmC2ZxR1Me0oITZrLsOY"
      - key: PORT
        value: "3000"
      - key: OWNER_NAME
        value: "ğ–¤ğ—†ğ—‰ğ—‚ğ—‹ğ–¾ ğ–³ğ–¾ğ–¼ğ—"
      - key: OWNER_NUMBER
        value: "+2348144250768"
      - key: OWNER_USERNAME
        value: "only_one_empire"
      - key: OWNER_CAPTION
        value: "Â© 2025â€“2026 ğ–¤ğ—†ğ—‰ğ—‚ğ—‹ğ–¾ ğ–³ğ–¾ğ–¼ğ—"
      - key: ADMIN_ID
        value: "7128227681"
      - key: CHANNELS
        value: "@cowrywise_gaming_channel"